### ISSUE TITLE
Consider chrome's version JSON

### ISSUE THREAD

**Issue by paulirish** [WhichBrowser/WhichBrowser#1]
http://omahaproxy.appspot.com/all.json is available if you want a data feed that's maintained for what is the stable version of Chrome etc.

more human readable version here https://googledrive.com/host/0B8R1QvA3x5IbWll3M0hIYXVLZlk/

dunno if this is useful to you.. but just FYI

**Comment by NielsLeenheer** [comment]
Took a while but the Chrome build numbers are now automatically updated from the Omahaproxy with each release.

BTW, is there a way to get the full release history, instead of just the recent release history:
http://omahaproxy.appspot.com/history
