### ISSUE TITLE
Internet Explorer 12 support

### ISSUE THREAD

**Issue by le717** [WhichBrowser/WhichBrowser#31]
You'll have fun with this one.

https://gist.github.com/jacobrossi/c9699b27df2f4e97c0bd

`Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0`

(Source from gabceb/jquery-browser-plugin#47)

This UA could break a lot of stuff if it stays in this form (and I'm sure it will).

**Comment by NielsLeenheer** [comment]
Fixed. Forgot to close this bug back in November. Btw this actually still IE11 in Edge mode.

**Comment by le717** [comment]
So IE 11 Edge and 12 now uses this UA? Oh my...
