### ISSUE TITLE
iOS 8.X not recognized

### ISSUE THREAD

**Issue by GustavHeinz** [WhichBrowser/WhichBrowser#32]
I think the recognition of iOS minor-Versions is messed up. The Useragent of iOS-devices (Version 8.1) is something like:

Mozilla/5.0 (iPhone; CPU iPhone OS 8_1 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4

Now whichbrowser is looking for /Version\/([0-9\\.]+)/u, however it should be looking for something like /OS ([0-9\\_]+)/u to get the real Version as the 'Version-Version' is not changing. I did this in line 3928 of the newest whichbrowser-version and it worked for me.

(unfortunately I have no time to make a pull request (and I'm pretty new to gitHub^^). I hope this spares you some time though)

**Comment by NielsLeenheer** [comment]
I'm not seeing any issues with iOS version detection with the latest versions.
