### ISSUE TITLE
Internet Explorer 11 - Enterprise mode - Browser and OS versions reported wrong

### ISSUE THREAD

**Issue by JakeSummers** [WhichBrowser/WhichBrowser#33]
Environment:

* Windows 8.1 
* Internet Explorer 11.0.9600

Steps: 

1. [Enable enterprise mode](http://msdn.microsoft.com/en-us/library/dn640699.aspx) using the registry
1. Navigate to whichbrowser.net
1. Result is: `You are using Internet Explorer 8.0 on Windows 7`.  Wrong browser version and wrong os version.

**Comment by NielsLeenheer** [comment]
If you go to whichbrowser.net, what is the user agent string listed there?
