### ISSUE TITLE
OS X 10.10.2

### ISSUE THREAD

**Issue by ron-wolf** [WhichBrowser/WhichBrowser#35]
Although the OS version is presented in the user agent string as “Macintosh; Intel Mac OS X 10_10_2” html5test still records it as “OS X Yosemite 10.10”.

**Comment by ron-wolf** [comment]
It’s like a ghost town out here.

**Comment by NielsLeenheer** [comment]
WhichBrowser records the whole version string, but the human readable string is limited to just the major and minor version number for aesthetic reasons.
