### ISSUE TITLE
why do you need php, npm support

### ISSUE THREAD

**Issue by chacliff** [WhichBrowser/WhichBrowser#37]
Without looking at the source, my first thought going over the Readme is why do you need php? Could you not come up with a Javascript solution that doesn't have a dependency on php? This would be really nice to have as straight javascript then it could just run with only the inclusion of a js file. 
Also i'm not sure how to use bower, but i am familiar with npm, it would be convenient if you could do a class npm install whichbrowser like many other modules. Which is i believe node support. This can probably just be marked as a question.

**Comment by NielsLeenheer** [comment]
Yes, it can be done in Javascript alone, but then every visitor needs to download the complete device database which is way too large. That is why you need to do server side detection.

**Comment by mariotsi** [comment]
I made a Node.js version because I can't find any other library with this grade of detection rate. You can find it here https://www.npmjs.com/package/which-browser
