### ISSUE TITLE
Edge version

### ISSUE THREAD

**Issue by jdalton** [WhichBrowser/WhichBrowser#47]
I noticed MS Edge is detected without a version number but other browsers are detected with their version numbers.

Based on the recent [MS blog guidance](https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/) Edge should be detected as Edge 12. See other tools like caniuse or es6-compat tables.
<table><tr><td>
![image](https://cloud.githubusercontent.com/assets/4303/10008459/a250842c-6083-11e5-9118-ba281ca52add.png)</td><td>
![image](https://cloud.githubusercontent.com/assets/4303/10008464/b09bf548-6083-11e5-8c52-b444d320a6aa.png)
</td><tr><table>

**Comment by NielsLeenheer** [comment]
I've updated WhichBrowser to detect the major version number of EdgeHTML. Edge itself is still without version number.

**Comment by jdalton** [comment]
I'm not sure what that means for things like HTML5Test? Will it display Edge 12?

**Comment by NielsLeenheer** [comment]
No, WhichBrowser is just used to identify the browser with which the user is visiting the site. And by default the rendering engine and version is not shown. So this change will not result in any visible change. On the backend it will make it easier to detect which score is coming from which version of EdgeHTML.

**Comment by jdalton** [comment]
The browser version is Edge 12, like Chrome 44, or Firefox 39.

**Comment by jdalton** [comment]
<img width="365" alt="screen shot 2015-09-22 at 12 41 18 am" src="https://cloud.githubusercontent.com/assets/4303/10013004/52b31ac6-60c2-11e5-95ec-c277a8a4419c.png">
<img width="310" alt="screen shot 2015-09-22 at 12 42 59 am" src="https://cloud.githubusercontent.com/assets/4303/10013006/54940a8a-60c2-11e5-87ea-7ee8c7cfda64.png">

**Comment by NielsLeenheer** [comment]
My impression from the link you posted is that:
- The upcoming version of Edge (the app) is 22
- The upcoming version of EdgeHTML (the rendering engine) is 13
- The version of the app is not expressed in the UA string
- The version of the app is not important
- "Edge 13" is just shorthand for "the version of Edge that uses EdgeHTML 13"

**Comment by NielsLeenheer** [comment]
The change I've made so far deals with the first four points. I'm still considering a way to do the last one. But to me it looks like giving the browser a version would be inaccurate.

**Comment by jdalton** [comment]
Naw, what they're calling the App version is for user interface features surrounding the web page itself, such as the address bar, tabs, Cortana, Reading View or Web Notes.

"we’re iterating this token to “Edge/13.*,” and will continue to update the token in the future according to the MAJOR.BUILD  schema. The major version number represents a significant platform release"

"For sites or other resources that are primarily concerned with tracking availability of web standards and other developer-facing features, we recommend tracking against the EdgeHTML version number"

The version in the UA token `Edge/13` represents what aligns with `Chrome/44`.

**Comment by jdalton** [comment]
So when you display it for reports it should be `Edge 13` not `Edge` and not `Edge 22`.

**Comment by NielsLeenheer** [comment]
I'm not trying to be difficult, but there are three separate things I have to deal with:

1) The label on the HTML5test result tables — I'll gladly change that to Edge 12 / 13
2) The internal representation of WhichBrowser
3) The human readable string that WhichBrowser outputs

The internal representation would look to me like: 
{ browser: { name: 'Edge' }, engine: { name: 'EdgeHTML', version: 13 }

And not:
{ browser: { name: 'Edge', version: 13 }, engine: { name: 'EdgeHTML' }

Why this internal representation? Because other browsers can also use EdgeHTML and I want to be able to identify which version of EdgeHTML they are using. And because having a version on the browser seems to conflict with the app version that Edge uses. Because the actual app version is not detectable I'd rather not use a version for the browser altogether.

The challenge would be to make human readable string still look like "Edge 13"

**Comment by jdalton** [comment]
I think you're overcomplicating it. There was mshtml.dll script.dll for IE's like IE 11. In Edge it's edgehtml.dll and chakra.dll but the browser is Edge 12 soon to be Edge 13.

**Comment by NielsLeenheer** [comment]
The internal representation is complicated for a reason. I get hundreds of thousands of different scores from visitors. I need to be able to identify these scores to be able to track changes. 

So let's say I have a specific version of UC Browser on Windows and I get 3 different scores for the same version number I need to know what the differences are. One might be using Trident on Windows 8, the other might be using EdgeHTML 12 and the last one EdgeHTML 13. Still all of them have the same browser version number. These differences can be detected and need to be able to be expressed in the internal representation of WhichBrowser.

Saying that "Edge/13" is Edge 13 is too simple.

**Comment by jdalton** [comment]
If your solution is on par with how Chrome is handled that's fine with me. My main concern is how it's displayed and tracked on HTML5test.

**Comment by jdalton** [comment]
Rock! Thanks @NielsLeenheer! I now see `Edge 13`.

Are you also planning on updating HTML5test for the `Edge` entry when comparing other browser to `Edge 12`?
